# -*- coding: utf-8 -*-
"""
Project Euler

Problem 45: Triangular, pentagonal, and hexagonal

Triangle, pentagonal, and hexagonal numbers are generated by the following
formulae:

Triangle         Tn=n(n+1)/2         1, 3,  6, 10, 15, ...
Pentagonal       Pn=n(3n−1)/2        1, 5, 12, 22, 35, ...
Hexagonal        Hn=n(2n−1)          1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

Analysis

"""

def pent(aNumber):
    return int(round((aNumber*(3*aNumber-1)/2),0))

def tri(aNumber):
    return int(round(aNumber*(aNumber+1)/2,0))

def hex(aNumber):
    return int(round(aNumber*(2*aNumber-1),0))

def invPent(n):
    return int(round(1/6+(1/36+2/3*n)**(0.5),0))

def invHex(n):
    return int(round(1/4+(1/16+n/2)**(0.5),0))


from time import time

if __name__ == '__main__':
    startTime = time()
    print("\n\n\n")

    maxToTry = 100
    flag = True
    while flag:
        triNoList = [0]*maxToTry
        pentNoDict = {}
        hexNoDict = {}

        for k in range(1, maxToTry):
            triK = tri(k)
            triNoList[k] = triK
            pentK = pent(k)
            pentNoDict[pentK] = True
            hexK = hex(k)
            hexNoDict[hexK] = True

        print("List, Dicts populated with", maxToTry, "entries.")

        for k, triK in enumerate(triNoList):
            if k % 1000 == 0:
                print("k:", k, flush=True)
            if triK in pentNoDict and triK in hexNoDict and k != 285 and k != 1:
                print("Found the next one:", k)
                flag = False
                break
        maxToTry *= 10

    totalTime = time() - startTime
    print("\n\nThe next triangle number after 285 that is also pentagonal"
          "and hexagonal is", k, triK, int(round((k*(k+1)/2),0)),
          invPent(triK), invHex(triK), pent(invPent(triK)),
          hex(invHex(triK)))
    print("Time to find:", '{:,.3f}'.format(totalTime))

"""
Result:

The next triangle number after 285 that is also pentagonaland hexagonal is
55385 1533776805 1533776805 31977 27693 1533776805 1533776805
Time to find: 1.378

"""
